###########################################################################
# Page tree
nav:
  - Home: index.md

  - Section 1:
      - Welcome: Section_1_0_Getting Started.md
      - 1 Course Structure and Projects: Section_1_i_Content.md

  - S2:
      - Introduction: Section_2_0_JavaScript Refresher.md
      - 1 Hello World!: Section_2_i_Content.md

  - S3:
      - Introduction: Section_3_0_React Essentials.md
      - 36 Components: Section_3_i_Components.md

  #- S3:
  #    - 31 Section Intro: Section_2_i5_Section Intro.md

###########################################################################
###########################################################################
# Project information
site_name: React Course Note #Xiaoyu NoteBook

site_author: Owen

# Copyright
copyright: Copyright &copy; 2015 - 2023 Owen

# Configuration
theme:
  #name: Litera #yeti #cerulean #gitbook #material #mkdocs #material
  name: material

  favicon: assets/water.png
  icon:
    logo: material/library #material/cat

  font:
    code: Roboto Mono

  features:
    - search.suggest
    - search.highlight
    - navigation.tracking
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    #- navigation.expand
    - navigation.top

    - navigation.instant ###
    - navigation.tabs ###
    #- navigation.tabs.sticky
    - content.tabs.link
    - content.code.copy
  palette:
    - scheme: default
      primary: amber #green
      accent: blue #green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

#Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tanyusheng
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/tan-yu-sheng-63
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/22048069
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCX0mNfkFoEHL2HNrfGK2gMA
    #- type: "github"
    #  link: "https://github.com/xxxx"
    #- type: "twitter"
    #  link: "https://twitter.com/xxxx"
    #- type: "linkedin"
    #  link: "https://www.linkedin.com/in/xxxx"

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
###########################################################################

